### ISSUE TITLE
Please add a tag to the v1.3 release

### ISSUE THREAD

**Issue by jreimone** [green-coding-berlin/eco-ci-energy-estimation#19]
The [v1.3 release]([v1.3 QoL and Feature Release](https://github.com/green-coding-berlin/eco-ci-energy-estimation/releases/tag/untagged)) is somehow untagged. Can you please add a tag for it so that it can be used precisely in workflows 🙏?

**Comment by ArneTR** [comment]
ups, sorrry that should not have happened. 

I untagged it earlier in a meeting for demo purposeses and forgot to re-add it.

[According to our discussion here](https://github.com/green-coding-berlin/eco-ci-energy-estimation/pull/4) the semantic version on Github Actions is quite flawed and you always have to remove and re-add tags to the newest release if you want to supply automatic updates to users.

WE also update the docs and will be supplying auto updates only for @v1 tag. So if you want that we encourage you to change it to that. This is the tag we will continuously update.

The @v1.3 will get stale over time ... even if we ever do a @v1.3.1 bugfix release as github actions does not pick that up

**Comment by ArneTR** [comment]
Just as an update: Of course we will keep the API from now on consistent in the @v1 branch so that no breaks occur. If we change switches or behaviour a new @v2 release will happen.

**Comment by jreimone** [comment]
Yes, thanks for the reminder. Your @v1 works perfectly 👍
