### ISSUE TITLE
Energy consumption mertrics as a GitHub PR Comment or Issue

### ISSUE THREAD

**Issue by ibakshay** [green-coding-berlin/eco-ci-energy-estimation#23]
I got to know about your project today, I have to say that your work is impressive and I really appreciate it :clap:. 

I would like to integrate this GitHub Action to my open source project and it will be great if this [energy consumption information and the energy graph](https://github.com/contributor-assistant/github-action/actions/runs/5202790541) is also posted as a **pull request comment** in the pull request. 

<img width="1468" alt="Screenshot 2023-06-07 at 20 09 54" src="https://github.com/green-coding-berlin/eco-ci-energy-estimation/assets/33329946/65818a00-aa2f-4716-9f2e-4cc9711253f8">

Do you have any plans to add this feature?

**Comment by ArneTR** [comment]
thx for the nice words :)

You mean like when Dependabot makes a PR for you? that sounds actually quite interesting.

Just let me re-iterate if I understood it correctly: Your repo is configured that way, that when a new PR is made automatically a Github Actions Workflow is triggered that runs a test.
Then, inside the Pull-Request conversation you want after the result if the workflow failed / succeeded also a comment that contains the energy, right?

@dan-mm Also pulling you in this conversation here.

**Comment by dan-mm** [comment]
That's an interesting idea, I like it. It seems like you can create comments using the github API, so I should be able to add a feature to support this optionally via a flag. I will add it to the list :-)

This is good feedback, thanks. I'm quite interested in knowing how people intend to use Eco-CI and specifically how people want the information displayed in their workflows.

**Comment by ibakshay** [comment]
>Your repo is configured that way, that when a new PR is made automatically a Github Actions Workflow is triggered that runs a test.

Yes, exactly.

>Then, inside the Pull-Request conversation you want after the result if the workflow failed / succeeded also a comment that contains the energy, right?

Yep! I would like to have the energy consumption information directly displayed in the Pull Request conversation as it makes it transparent for the contributors who create a Pull Request. 

For example: [PR comment from dependabot](https://github.com/contributor-assistant/github-action/pull/124#issue-1520066977).
<img width="1017" alt="Screenshot 2023-06-08 at 13 42 18" src="https://github.com/green-coding-berlin/eco-ci-energy-estimation/assets/33329946/0452f7cf-e8fb-4b80-b39a-fd17e0858397">

**Comment by ArneTR** [comment]
That sounds like a great feature and we will most likely schedule that in. Probably something like end of the month I guess.

If you @ibakshay are however interested in doing a contribution we are also happy to take a PR and provide some guidance :)

**Comment by ibakshay** [comment]
> That's an interesting idea, I like it. It seems like you can create comments using the github API, so I should be able to add a feature to support this optionally via a flag. I will add it to the list :-)
> 

Sounds great! GitHub APIs to create a PR comment or issue comment is easy to consume and well documented. You can use this [GitHub Actions token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) authentication to post a PR comment. With this approach, you don't need to ask for a personal access token from the end-user.

**Comment by dan-mm** [comment]
This feature has been added in the 2.1 release: https://github.com/green-coding-berlin/eco-ci-energy-estimation/releases/tag/v2.1
