### ISSUE TITLE
Please remove my repo from the measurement overview 🙏

### ISSUE THREAD

**Issue by jreimone** [green-coding-berlin/eco-ci-energy-estimation#25]
Hi everyone,
again I want to thank you for your great GHA. It's running in my repos and I also generate nice graphs since we can consume the measurements as json now. I just noticed that our repo `Staffbase/testio-management` is visible at the very bottom [here](https://metrics.green-coding.berlin/ci-index.html). Can you please remove it from there since the measures were contributed before one could opt-out from uploading the data. I would appreciate that.

**Comment by ArneTR** [comment]
absolutely. Has been removed
