### ISSUE TITLE
Look into why Dependabot is not triggering on Eco-CI public versions

### ISSUE THREAD

**Issue by ArneTR** [green-coding-berlin/eco-ci-energy-estimation#37]

**Comment by dan-mm** [comment]
Ok, I finally understand what was happening here. The short version - the commit hash you pin to *has* to correlate to the specific commit of a tag. The commit hash I used to test was a random one from between two tags - dependabot does not know what version to resolve this to so it didn't do anything

I tested this out on a private repo extensively, and dependabot triggers for Eco-CI just fine if you tag it with @v#, or with a commit hash that specifically matches a tag. Everything in GMT references via the @v2 tag so it should be ok.

I've also updated the eco-ci readme to reference the commit hash method now that I understand it, and updated the readme manaully / closed this PR with a comment: https://github.com/green-coding-berlin/eco-ci-energy-estimation/pull/4

One last, unrelated note: while working on this I found the dependabot logs, and while looking through them I saw that our dependabot is not properly checking/updating Dockerfiles: https://github.com/green-coding-berlin/green-metrics-tool/network/updates/711614063 . Something there is not setup correctly - I can take a look at this, but will work on the other things on my list first.
