### ISSUE TITLE
PR-Comment fails on Github Enterprise

### ISSUE THREAD

**Issue by dan-mm** [green-coding-berlin/eco-ci-energy-estimation#48]
- the url we use for the API call to post PR comments uses the public github API.
- this fails for github enterprise.
- there is probably a context or environment variable for the correct api url link that we should use instead

**Comment by ArneTR** [comment]
@jreimone Thanks for the input
@dan-mm Can you link the source why this ticket was opened from our side so we can narrow it down

**Comment by dan-mm** [comment]
@ArneTR - Unfortunately I can't link it - this was from the conference workshop, one of the attendees mentioned it to me in person, and I wrote the ticket in that moment. Specifically he mentioned that they were hosting their own github API (possible with enterprise), so he needed the url that we call to be configurable. 
Its possible that in @jreimone didn't have this issue if they were still using github's standard api.

The work to support this has already done here: https://github.com/green-coding-berlin/eco-ci-energy-estimation/commit/12c5a5a332fc2d1cb605acd00759fde7c2c87c24

**Comment by jreimone** [comment]
@dan-mm is correct, we use the standard API.

**Comment by ArneTR** [comment]
closed for now. Please reopen if problem occurs again for anyone.
