### ISSUE TITLE
Add a workflow that tests the action for this repo

### ISSUE THREAD

**Issue by rajbos** [green-coding-berlin/eco-ci-energy-estimation#8]
Nice to show how much data this action uses for it's own repo, as well as having a working example + output data. 
Also works as an integration tests on PR's to make sure things work as expected 😃. I can help with this if needed / wanted.

**Comment by ArneTR** [comment]
Hey @rajbos ,

jep, actually a really nice idea. The extension itself obviously has an overhead, and it would be nice to know how much really is your code, and how much just ist because of our action.

Wann give it a go and submit a pull request?

I will put our engineer on review
