### ISSUE TITLE
Show the numbers of the calculation on the same line

### ISSUE THREAD

**Issue by rajbos** [green-coding-berlin/eco-ci-energy-estimation#9]
Perhaps a table would help with the readability, but for me the current setup does not look nice and makes it harder to read. This could be combined with the work in #7.

![image](https://user-images.githubusercontent.com/6085745/230924567-43550e5f-5cc8-421d-a2f5-2f95848e9802.png)

**Comment by ArneTR** [comment]
Yeah, I agree, that can be optimized. 

@dan-mm Can you try a markdown table here?

**Comment by dan-mm** [comment]
@rajbos I updated the eco-ci so it now displays a graph, and only on display-results.

The downside is now you have to call display-results to see anything, as it no longer displays spot results on get-measurement. I could display a mini-table on each get-measurement call, but I suspect just one final table is neater and more in line with what people want anyways. Thoughts?

![image](https://user-images.githubusercontent.com/33732895/232720467-4cf53e41-42a4-4c01-a2cb-d3d512062a27.png)

**Comment by rajbos** [comment]
I prefer to explicitly call for the summary then having that info in multiple places. 

Love they the labels are included of the measurements in between 👍.

**Comment by dan-mm** [comment]
Awesome, thanks for taking a look at it!
